### ISSUE TITLE
Better definition of not cancelled flights in flights dataset

### ISSUE THREAD

**Issue by dracodoc** [hadley/r4ds#117]
In `4.7.2 Missing values`, not cancelled flights are defined as

`not_cancelled <- filter(flights, !is.na(dep_delay), !is.na(arr_delay))`

However there are some mismatches of the NAs in time and delay:

|dep_time NA's | dep_delay NA's | arr_time NA's | arr_delay NA's |
| :--  | :--  | :--  | :--  |
| 8255 | 8255 | 8713 | 9430 |

The much bigger number of arr_delay NA's turned out to be errors that can be recovered:

```
> flights %>% 
+   filter(!is.na(arr_time), is.na(arr_delay)) %>%
+   select(dep_time:flight)
Source: local data frame [717 x 8]

   dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay carrier flight
      (int)          (int)     (dbl)    (int)          (int)     (dbl)   (chr)  (int)
1      1525           1530        -5     1934           1805        NA      MQ   4525
2      1528           1459        29     2002           1647        NA      EV   3806
```
So we can just recalculate arr_delay for these records. After the recalculation, a better definition of not cancelled flights could be:

`not_cancelled <- filter(flights, !is.na(dep_time), !is.na(arr_time))`

Of course this may be more suit for a different topic or chapter.

**Comment by hadley** [comment]
Good point - I don't want to get into this in the text, so I made it an exercise.

**Comment by cbrnr** [comment]
Still, this definition is used in section 5.6.2 - Missing Values, and it is confusing that the two methods presented here (the first uses `na.rm=TRUE` whereas the second uses `filter`) produce different results. This should be clarified in the text, because right now it reads as if these two alternatives do the same thing (*In this case, where missing values represent cancelled flights, we could also tackle the problem by first removing the cancelled flights.*).
