### ISSUE TITLE
Coalesce example does not exchange Nas for 0s

### ISSUE THREAD

**Issue by duhalde** [hadley/r4ds#1223]
See below.

df_miss |> 
  [mutate](https://dplyr.tidyverse.org/reference/mutate.html)(
    [across](https://dplyr.tidyverse.org/reference/across.html)(a:d, \(x) [abs](https://rdrr.io/r/base/MathFun.html)(x), .names = "{.col}_abs")
  )
#> # A tibble: 5 × 8
#>        a      b      c      d  a_abs  b_abs  c_abs d_abs
#>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl>
#> 1 NA     -0.463 NA      2.13  NA      0.463 NA     2.13 
#> 2 -0.382 -0.980 NA      0.704  0.382  0.980 NA     0.704
#> 3  0.434 NA     -1.06   0.715  0.434 NA      1.06  0.715
#> 4  1.06   1.21  -0.796 -1.09   1.06   1.21   0.796 1.09 
#> 5  0.424 -1.28  -0.785  0.402  0.424  1.28   0.785 0.402

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.
