### ISSUE TITLE
Section 3.7.1 exercise 6: Plots 1 and 2 are equal

### ISSUE THREAD

**Issue by sebschub** [hadley/r4ds#439]
In the exercise 6 of the  Geometric objects subsection of Data visualisation,
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
      geom_point() + 
      geom_smooth(aes(group = drv), se = FALSE)
```
and
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
      geom_smooth(aes(group = drv), se = FALSE) +
      geom_point()
```
produce exactly the same plot, don't they? This doesn't make sense in this exercise.

**Comment by fdabl** [comment]
hi,

this should be exercise 3.6.1, right? I don't think they produce exactly the same plot. The first plot overlays the points with the fitted function, while the second plot overlays the fitted function with the points.

I just started working through the book myself, and found this example also a bit odd to reproduce (because when you plot them with normal size in RStudio, they really look the same).

cheers,
Fabian

**Comment by hadley** [comment]
Now changed to have more obvious difference. Thanks!
