### ISSUE TITLE
Instructor's manual for exercises

### ISSUE THREAD

**Issue by bensoltoff** [hadley/r4ds#472]
I'm currently using R for Data Science for a [graduate computing course in the social sciences](https://uc-cfss.github.io/). I don't assign the exercises for homework, but some students are working through them for practice and asked if there is a solution key to compare their answers to. I don't have the time to go through and work all the exercises myself, but I'm happy to help them troubleshoot individual exercises. Is there a plan to release an instructor's manual for the exercises in the book?

**Comment by schwarzm3283** [comment]
Second

**Comment by chopper55** [comment]
Third

**Comment by hadley** [comment]
There isn't a plan, but I'm hoping people in the community might come together and work on it...

**Comment by bensoltoff** [comment]
I started working on an answer key awhile back for my class, available [here](http://cfss.uchicago.edu/r4ds_solutions.html). Some other partial keys can be found floating around online. [This one seems the most complete so far.](https://jrnold.github.io/e4qf/)

**Comment by chendaniely** [comment]
where do you suggest the community to put together an official solutions manual?
as a PR into a `solutions` folder here? or should a more 'official' repository be set up somewhere so we don't have people re-inventing the wheel?

I can test out a few methods since I'm currently using the book to teach and have some students that can start answering questions (that i'll check)

**Comment by hadley** [comment]
https://jrnold.github.io/r4ds-exercise-solutions/
