### ISSUE TITLE
Inconsistent use of third and first person in ch 3

### ISSUE THREAD

**Issue by EdwinTh** [hadley/r4ds#642]
First, in 3.3 it is written:
"(If you prefer British English, like Hadley, you can use colour instead of color.)"

Later, at the start of 3.4:
"I have been writing R code for years, and every day I still write code that doesn’t work!"

I don't have a preference for one or the other, but I think it would be cleaner if it was consistently the one or the other.

**Comment by courtiol** [comment]
This is actually true that the first person is used often throughout the book and seems to refer to @garrettgman. In the printed edition I have (second edition I think) it feels even weirder because @hadley is listed as the first author. I know, many would say "who cares", but I believe that consistently using "we" would avoid distracting some of the readers and would give some credit to @hadley. A simple search for "I " would probably identify most cases since I do not remember encountering the third person in other sentence that the one quoted above.
