### ISSUE TITLE
Chapter 12.6: Final code is not the same as previous snippets

### ISSUE THREAD

**Issue by Shurakai** [hadley/r4ds#854]
Maybe not very important, but in the final code snippet in Section 12.6 the first `separate()` call does not have a `sep` argument, whereas the same call in the previously shown snippets defines `sep="_"` explicitly. I'm aware that the default value of sep matches all non-alphanumerical characters but I thought I'd still let you know.

` separate(key, c("new", "var", "sexage")) %>% `

vs

`separate(key, c("new", "type", "sexage"), sep = "_")`

**Comment by JorgeRiescoDavila** [comment]
In the previous snippets a new variable called `names_from` is created, 
```
who2 <- who1 %>% 
  mutate(names_from = stringr::str_replace(key, "newrel", "new_rel"))
```
this causes a problem later becuase the variable we `separate` is `key`, instead of `names_from` . However in the variable `key` `newrel` was not changed to `new_rel`, that creates some missing values. Check for example `who5[243,]`. Also the variable `names_from` remains on the final tibble.
```
who3 <- who2 %>% 
  separate(key, c("new", "type", "sexage"), sep = "_")
```
I think this must solve the problem:
```
who2 <- who1 %>% 
  mutate(key = stringr::str_replace(key, "newrel", "new_rel"))
```

**Comment by hadley** [comment]
We now take a different approach, avoiding this problem: https://r4ds.hadley.nz/data-tidy.html#case-study
